#$qsConfig = ii
exec = hyprctl dispatch submap global
submap = global

# Environment variables
source=hyprland/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/keybinds.conf

monitor=eDP-1,2256x1504@60.00,320x824,1.00
monitor=DP-4,1440x900@74.98,2624x1184,1.00
