$qsConfig = ii
exec = hyprctl dispatch submap global
submap = global
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# Environment variables
source=hyprland/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/keybinds.conf

monitor=eDP-1,2256x1504@60.00,320x824,1.00
monitor=DP-3,1440x900@59.89,2576x856,0.75
